# Lando <https://lando.dev> development environment
# Usage:
# `lando start`: To start it up
# `lando stop`: To stop it and resume latter
# `lando destroy && rm -rf wp-www`: If you want to start again
# cSpell:ignore appserver lando lndo

name: simple-ldap-plugin
recipe: wordpress

config:
  via: nginx
  webroot: wp-www # cspell:disable-line
  database: mariadb
  php: "8.0"
  composer_version: "2"

services:
  appserver:
    run:
      - |
        wp --path=/app/wp-www core download
        wp --path=/app/wp-www config create --dbhost=database.internal --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --extra-php="define('WP_DEBUG', true);"
        wp --path=/app/wp-www core install --title="WP Dev" --url=https://wp.lndo.site --admin_user=admin --admin_password=password --admin_email=admin@example.com
    overrides:
      volumes:
        - ./:/app/wp-www/wp-content/plugins/simple-ldap-login

proxy:
  appserver_nginx:
    - wp.lndo.site

tooling:
  wp:
    service: appserver
    cmd: /usr/local/bin/wp
    dir: /app/wp-www
